INSERT INTO education_level (name) VALUES
('Nursery'),
('Preschool'),
('Kindergarten'),
('Elementary School'),
('Middle School'),
('High School'),
('Vocational Training Programs'),
('Technical Schools'),
('Associate''s Degree'),
('Bachelor''s Degree'),
('Master''s Degree'),
('Doctorate (Ph.D.)'),
('Medical School'),
('Law School'),
('Business School'),
('Engineering School'),
('Art and Design Schools'),
('Military Training'),
('Police Academy'),
('Online Courses'),
('Distance Learning Programs'),
('Certificate Programs'),
('Workshops and Seminars'),
('Education for Individuals with Disabilities'),
('Inclusive Education Programs'),
('English as a Second Language (ESL)'),
('Foreign Language Schools'),
('Art Schools'),
('Music Schools and Conservatories'),
('Sports Academies'),
('Physical Education Programs'),
('Theological Seminaries'),
('Religious Studies Programs'),
('Community Colleges'),
('Lifelong Learning Programs');
