INSERT INTO locations (country, city) VALUES
("Portugal", "Abobada"),
("Portugal", "Abrantes"),
("Portugal", "Acores"),
("Portugal", "Aguada de Cima"),
("Portugal", "Agualva"),
("Portugal", "Agucadoura"),
("Portugal", "Aguiar da Beira Municipality"),
("Portugal", "Alandroal"),
("Portugal", "Albergaria-a-Velha"),
("Portugal", "Albufeira"),
("Portugal", "Alcabideche"),
("Portugal", "Alcacer do Sal"),
("Portugal", "Alcains"),
("Portugal", "Alcanede"),
("Portugal", "Alcanena"),
("Portugal", "Alcobaca"),
("Portugal", "Alcochete"),
("Portugal", "Alcoentre"),
("Portugal", "Aldeia de Paio Pires"),
("Portugal", "Aldeia do Meio"),
("Portugal", "Aldeia dos Fernandes"),
("Portugal", "Alenquer"),
("Portugal", "Alfarelos"),
("Portugal", "Alfena"),
("Portugal", "Alfornelos"),
("Portugal", "Alfragide"),
("Portugal", "Alges"),
("Portugal", "Algoz"),
("Portugal", "Algueirao"),
("Portugal", "Alhandra"),
("Portugal", "Alhos Vedros"),
("Portugal", "Aljezur"),
("Portugal", "Aljustrel"),
("Portugal", "Almada"),
("Portugal", "Almancil"),
("Portugal", "Almargem"),
("Portugal", "Almeirim"),
("Portugal", "Almodovar"),
("Portugal", "Alpiarca"),
("Portugal", "Alportel"),
("Portugal", "Alqueidao da Serra"),
("Portugal", "Alter do Chao"),
("Portugal", "Altura"),
("Portugal", "Alvaiazere"),
("Portugal", "Alvarinhos"),
("Portugal", "Alvelos"),
("Portugal", "Alverca"),
("Portugal", "Amadora"),
("Portugal", "Amarante"),
("Portugal", "Amares"),
("Portugal", "Amiaes de Cima"),
("Portugal", "Amor"),
("Portugal", "Amora"),
("Portugal", "Amoreira"),
("Portugal", "Amorim"),
("Portugal", "Anadia"),
("Portugal", "Anta"),
("Portugal", "Apulia"),
("Portugal", "Arazede"),
("Portugal", "Arco da Calheta"),
("Portugal", "Arcos de Valdevez"),
("Portugal", "Arcozelo"),
("Portugal", "Arganil"),
("Portugal", "Argoncilhe"),
("Portugal", "Armacao de Pera"),
("Portugal", "Arouca"),
("Portugal", "Arraiolos"),
("Portugal", "Arrifana"),
("Portugal", "Arronches"),
("Portugal", "Arruda dos Vinhos"),
("Portugal", "Arvore"),
("Portugal", "Assumar"),
("Portugal", "Atalaia"),
("Portugal", "Atouguia da Baleia"),
("Portugal", "Avanca"),
("Portugal", "Aveiras de Cima"),
("Portugal", "Aveiro"),
("Portugal", "Avelar"),
("Portugal", "Avidos"),
("Portugal", "Avintes"),
("Portugal", "Azoia"),
("Portugal", "Azueira"),
("Portugal", "Azurem"),
("Portugal", "Baguim"),
("Portugal", "Baguim do Monte"),
("Portugal", "Baleia"),
("Portugal", "Baltar"),
("Portugal", "Barcarena"),
("Portugal", "Barcelos"),
("Portugal", "Barreiro"),
("Portugal", "Barrosas"),
("Portugal", "Basto"),
("Portugal", "Batalha"),
("Portugal", "Beira"),
("Portugal", "Beja"),
("Portugal", "Belas"),
("Portugal", "Belmonte"),
("Portugal", "Bemfica"),
("Portugal", "Benafim"),
("Portugal", "Benavente"),
("Portugal", "Benedita"),
("Portugal", "Bicesse"),
("Portugal", "Bico"),
("Portugal", "Boavista"),
("Portugal", "Bobadela"),
("Portugal", "Boliqueime"),
("Portugal", "Bombarral"),
("Portugal", "Borba"),
("Portugal", "Boticas"),
("Portugal", "Bouca"),
("Portugal", "Braga"),
("Portugal", "Braganca"),
("Portugal", "Brito"),
("Portugal", "Bucelas"),
("Portugal", "Buraca"),
("Portugal", "Cabanelas"),
("Portugal", "Cabeceiras de Basto"),
("Portugal", "Cabeco de Vide"),
("Portugal", "Cabecudos"),
("Portugal", "Cabrela"),
("Portugal", "Cacela"),
("Portugal", "Cacem"),
("Portugal", "Cacilhas"),
("Portugal", "Cadaval"),
("Portugal", "Caldas"),
("Portugal", "Caldas da Rainha"),
("Portugal", "Caldas das Taipas"),
("Portugal", "Caldas de Sao Jorge"),
("Portugal", "Caldas de Vizela"),
("Portugal", "Calvao"),
("Portugal", "Calvaria de Cima"),
("Portugal", "Camarate"),
("Portugal", "Caminha"),
("Portugal", "Campanario"),
("Portugal", "Campia"),
("Portugal", "Campinho"),
("Portugal", "Campo"),
("Portugal", "Campo Maior"),
("Portugal", "Canecas"),
("Portugal", "Canedo"),
("Portugal", "Canedo"),
("Portugal", "Canelas"),
("Portugal", "Canhas"),
("Portugal", "Canical"),
("Portugal", "Canico"),
("Portugal", "Canidelo"),
("Portugal", "Cano"),
("Portugal", "Cantanhede"),
("Portugal", "Caparica"),
("Portugal", "Caramulo"),
("Portugal", "Carapinheira"),
("Portugal", "Carcavelos"),
("Portugal", "Carnaxide"),
("Portugal", "Carrazedo"),
("Portugal", "Carregado"),
("Portugal", "Carrico"),
("Portugal", "Cartaxo"),
("Portugal", "Carvalhal"),
("Portugal", "Carvalho"),
("Portugal", "Carvalhosa"),
("Portugal", "Carvoeiro"),
("Portugal", "Casal"),
("Portugal", "Casal da Areia"),
("Portugal", "Cascais"),
("Portugal", "Castanheira do Ribatejo"),
("Portugal", "Castelejo"),
("Portugal", "Castelo"),
("Portugal", "Castelo Branco"),
("Portugal", "Castelo de Paiva"),
("Portugal", "Castro Daire"),
("Portugal", "Castro Marim"),
("Portugal", "Castro Verde Municipality"),
("Portugal", "Catraia de Sao Paio"),
("Portugal", "Cavaleiros"),
("Portugal", "Cavaloes"),
("Portugal", "Caxias"),
("Portugal", "Ceira"),
("Portugal", "Celorico de Basto"),
("Portugal", "Cercal"),
("Portugal", "Cernache"),
("Portugal", "Cesar"),
("Portugal", "Chao de Couce"),
("Portugal", "Charneca"),
("Portugal", "Chaves"),
("Portugal", "Cidade"),
("Portugal", "Cinfaes"),
("Portugal", "Coimbra"),
("Portugal", "Coimbra"),
("Portugal", "Colares"),
("Portugal", "Colmeias"),
("Portugal", "Condeixa-a-Nova"),
("Portugal", "Constance"),
("Portugal", "Constancia"),
("Portugal", "Corroios"),
("Portugal", "Cortegaca"),
("Portugal", "Costa de Caparica"),
("Portugal", "Costa de Lavos"),
("Portugal", "Covilha"),
("Portugal", "Creixomil"),
("Portugal", "Cruz Quebrada"),
("Portugal", "Cuba"),
("Portugal", "Cucujaes"),
("Portugal", "Dalvares"),
("Portugal", "Damaia"),
("Portugal", "Darque"),
("Portugal", "Dois Portos"),
("Portugal", "Dona Maria"),
("Portugal", "Dossaos"),
("Portugal", "Eixo"),
("Portugal", "Elvas"),
("Portugal", "Encarnacao"),
("Portugal", "Entroncamento"),
("Portugal", "Entroncamento"),
("Portugal", "Ericeira"),
("Portugal", "Ermidas"),
("Portugal", "Escapaes"),
("Portugal", "Escoural"),
("Portugal", "Esmoriz"),
("Portugal", "Espinho"),
("Portugal", "Esposende"),
("Portugal", "Estarreja"),
("Portugal", "Estoi"),
("Portugal", "Estombar"),
("Portugal", "Estoril"),
("Portugal", "Estremoz"),
("Portugal", "Evora"),
("Portugal", "Fafe"),
("Portugal", "Famoes"),
("Portugal", "Fanzeres"),
("Portugal", "Fao"),
("Portugal", "Faro"),
("Portugal", "Feira"),
("Portugal", "Felgueiras"),
("Portugal", "Felgueiras"),
("Portugal", "Felgueiras"),
("Portugal", "Ferradosa"),
("Portugal", "Ferreira"),
("Portugal", "Ferreira do Alentejo"),
("Portugal", "Ferrel"),
("Portugal", "Ferro"),
("Portugal", "Fiaes"),
("Portugal", "Figueira da Foz Municipality"),
("Portugal", "Figueira de Lorvao"),
("Portugal", "Figueiro dos Vinhos"),
("Portugal", "Fogueteiro"),
("Portugal", "Folgados"),
("Portugal", "Forte"),
("Portugal", "Foz do Sousa"),
("Portugal", "Fradelos"),
("Portugal", "Freamunde"),
("Portugal", "Frielas"),
("Portugal", "Funchal"),
("Portugal", "Fundao"),
("Portugal", "Gafanha da Nazare"),
("Portugal", "Galiza"),
("Portugal", "Gandara dos Olivais"),
("Portugal", "Gandra"),
("Portugal", "Garruchas"),
("Portugal", "Gemunde"),
("Portugal", "Godim"),
("Portugal", "Golega"),
("Portugal", "Gondomar"),
("Portugal", "Gouveia"),
("Portugal", "Graca"),
("Portugal", "Gradil"),
("Portugal", "Grandola"),
("Portugal", "Granja"),
("Portugal", "Granja do Ulmeiro"),
("Portugal", "Grijo"),
("Portugal", "Guarda"),
("Portugal", "Guardizela"),
("Portugal", "Guia"),
("Portugal", "Guimaraes"),
("Portugal", "Gulpilhares"),
("Portugal", "Igreja Nova"),
("Portugal", "Igreja Nova"),
("Portugal", "Ilhavo"),
("Portugal", "Infesta"),
("Portugal", "Joane"),
("Portugal", "Jovim"),
("Portugal", "Juncal"),
("Portugal", "Lagarinhos"),
("Portugal", "Lago"),
("Portugal", "Lagoa"),
("Portugal", "Lagoa"),
("Portugal", "Lagoa"),
("Portugal", "Lagoas"),
("Portugal", "Lagos"),
("Portugal", "Lajes"),
("Portugal", "Lamego"),
("Portugal", "Landim"),
("Portugal", "Lavos"),
("Portugal", "Lavra"),
("Portugal", "Lavradio"),
("Portugal", "Leca da Palmeira"),
("Portugal", "Leca do Bailio"),
("Portugal", "Leiria"),
("Portugal", "Linda a Velha"),
("Portugal", "Linhaceira"),
("Portugal", "Linho"),
("Portugal", "Lisbon"),
("Portugal", "Lordelo"),
("Portugal", "Loule"),
("Portugal", "Lourel de Baixo"),
("Portugal", "Loures"),
("Portugal", "Lourical"),
("Portugal", "Lourosa"),
("Portugal", "Lousa"),
("Portugal", "Lousada"),
("Portugal", "Lousado"),
("Portugal", "Macas de Caminho"),
("Portugal", "Maceda"),
("Portugal", "Macedo de Cavaleiros"),
("Portugal", "Maceira"),
("Portugal", "Machico"),
("Portugal", "Macieira da Lixa"),
("Portugal", "Madeira"),
("Portugal", "Mafra"),
("Portugal", "Maia"),
("Portugal", "Malveira"),
("Portugal", "Malveira da Serra"),
("Portugal", "Mamouros"),
("Portugal", "Mangualde"),
("Portugal", "Manique de Baixo"),
("Portugal", "Manique do Intendente"),
("Portugal", "Marco"),
("Portugal", "Marco de Canaveses"),
("Portugal", "Margaride"),
("Portugal", "Marinha"),
("Portugal", "Marinha Grande"),
("Portugal", "Marinhais"),
("Portugal", "Marteleira"),
("Portugal", "Martinganca"),
("Portugal", "Massama"),
("Portugal", "Massarelos"),
("Portugal", "Matosinhos Municipality"),
("Portugal", "Mealhada"),
("Portugal", "Mem Martins"),
("Portugal", "Mesao Frio"),
("Portugal", "Mesao Frio"),
("Portugal", "Mexilhoeira Grande"),
("Portugal", "Milharado"),
("Portugal", "Milhazes"),
("Portugal", "Minde"),
("Portugal", "Mira"),
("Portugal", "Mira"),
("Portugal", "Miranda do Corvo"),
("Portugal", "Miranda do Douro"),
("Portugal", "Mirandela"),
("Portugal", "Mocarria"),
("Portugal", "Modivas"),
("Portugal", "Moita"),
("Portugal", "Moncao"),
("Portugal", "Monchique"),
("Portugal", "Monforte"),
("Portugal", "Monsanto"),
("Portugal", "Monsaraz"),
("Portugal", "Montalvo"),
("Portugal", "Monte Estoril"),
("Portugal", "Montelavar"),
("Portugal", "Montemor-o-Novo"),
("Portugal", "Montemor-o-Velho"),
("Portugal", "Montes"),
("Portugal", "Montes"),
("Portugal", "Montijo"),
("Portugal", "Moreira de Conegos"),
("Portugal", "Mortagua"),
("Portugal", "Moscavide"),
("Portugal", "Moura"),
("Portugal", "Moura"),
("Portugal", "Moure"),
("Portugal", "Mourisca do Vouga"),
("Portugal", "Mozelos"),
("Portugal", "Muro"),
("Portugal", "Murtede"),
("Portugal", "Murteira"),
("Portugal", "Nadadouro"),
("Portugal", "Negrelos"),
("Portugal", "Neiva"),
("Portugal", "Nelas"),
("Portugal", "Nespereira"),
("Portugal", "Nine"),
("Portugal", "Nisa"),
("Portugal", "Nogueira"),
("Portugal", "Nogueira da Regedoura"),
("Portugal", "Nogueira do Cravo"),
("Portugal", "Obidos"),
("Portugal", "Obidos"),
("Portugal", "Odemira"),
("Portugal", "Odivelas"),
("Portugal", "Oeiras"),
("Portugal", "Oia"),
("Portugal", "Olhao"),
("Portugal", "Olhos de Agua"),
("Portugal", "Olivais"),
("Portugal", "Olivais"),
("Portugal", "Olival"),
("Portugal", "Oliveira"),
("Portugal", "Oliveira do Bairro"),
("Portugal", "Oliveira do Douro"),
("Portugal", "Oliveira do Hospital"),
("Portugal", "Ortiga"),
("Portugal", "Ota"),
("Portugal", "Ourem"),
("Portugal", "Ourique"),
("Portugal", "Outeiro"),
("Portugal", "Ovar"),
("Portugal", "Paco de Arcos"),
("Portugal", "Paderne"),
("Portugal", "Palhaca"),
("Portugal", "Palhais"),
("Portugal", "Palmeira"),
("Portugal", "Palmela"),
("Portugal", "Parada de Gonta"),
("Portugal", "Parada do Bispo"),
("Portugal", "Paraiso"),
("Portugal", "Parchal"),
("Portugal", "Pardilho"),
("Portugal", "Parede"),
("Portugal", "Paredes"),
("Portugal", "Paredes"),
("Portugal", "Paredes da Beira"),
("Portugal", "Paredes de Coura"),
("Portugal", "Pataias"),
("Portugal", "Paul"),
("Portugal", "Pechao"),
("Portugal", "Pedreiras"),
("Portugal", "Pedroso"),
("Portugal", "Pedroucos"),
("Portugal", "Pegoes Velhos"),
("Portugal", "Penacova"),
("Portugal", "Penafiel"),
("Portugal", "Penedono"),
("Portugal", "Penela"),
("Portugal", "Penha Garcia"),
("Portugal", "Peniche"),
("Portugal", "Penteado"),
("Portugal", "Pereira"),
("Portugal", "Pero Pinheiro"),
("Portugal", "Pevidem"),
("Portugal", "Piedade"),
("Portugal", "Pinhal"),
("Portugal", "Pinhal Novo"),
("Portugal", "Pinheiro"),
("Portugal", "Pinheiro da Bemposta"),
("Portugal", "Pinheiro de Azere"),
("Portugal", "Poceirao"),
("Portugal", "Poco Barreto"),
("Portugal", "Poiares"),
("Portugal", "Polima"),
("Portugal", "Pombal"),
("Portugal", "Ponta"),
("Portugal", "Ponta Delgada"),
("Portugal", "Ponta do Sol"),
("Portugal", "Ponte"),
("Portugal", "Ponte da Barca"),
("Portugal", "Ponte de Lima"),
("Portugal", "Ponte de Sor"),
("Portugal", "Ponte de Vagos"),
("Portugal", "Pontevel"),
("Portugal", "Pontinha"),
("Portugal", "Portalegre"),
("Portugal", "Portel"),
("Portugal", "Portela"),
("Portugal", "Portimao"),
("Portugal", "Porto"),
("Portugal", "Porto"),
("Portugal", "Porto"),
("Portugal", "Porto"),
("Portugal", "Porto Alto"),
("Portugal", "Porto da Cruz"),
("Portugal", "Porto de Mos"),
("Portugal", "Porto Moniz"),
("Portugal", "Porto Salvo"),
("Portugal", "Povoa"),
("Portugal", "Povoa"),
("Portugal", "Povoa da Galega"),
("Portugal", "Povoa de Lanhoso"),
("Portugal", "Povoa de Santa Iria"),
("Portugal", "Povoa de Santo Adriao"),
("Portugal", "Povoa do Forno"),
("Portugal", "Prado"),
("Portugal", "Pragal"),
("Portugal", "Praia da Vitoria"),
("Portugal", "Praia de Mira"),
("Portugal", "Praia do Almoxarife"),
("Portugal", "Praia do Carvoeiro"),
("Portugal", "Praia do Ribatejo"),
("Portugal", "Prazins"),
("Portugal", "Prime"),
("Portugal", "Proenca-a-Nova"),
("Portugal", "Quarteira"),
("Portugal", "Quejas"),
("Portugal", "Queluz"),
("Portugal", "Queluz de Baixo"),
("Portugal", "Quinchaes"),
("Portugal", "Quinta"),
("Portugal", "Quinta"),
("Portugal", "Quinta do Anjo"),
("Portugal", "Ramada"),
("Portugal", "Ramo"),
("Portugal", "Rana"),
("Portugal", "Real"),
("Portugal", "Rebordosa"),
("Portugal", "Recarei"),
("Portugal", "Redondo"),
("Portugal", "Regueira de Pontes"),
("Portugal", "Reguengo Grande"),
("Portugal", "Reguengos de Monsaraz"),
("Portugal", "Riachos"),
("Portugal", "Riba de Ave"),
("Portugal", "Ribeira Brava"),
("Portugal", "Ribeira Grande"),
("Portugal", "Ribeirao"),
("Portugal", "Rinchoa"),
("Portugal", "Rio de Moinhos"),
("Portugal", "Rio de Mouro"),
("Portugal", "Rio Maior"),
("Portugal", "Rio Tinto"),
("Portugal", "Romariz"),
("Portugal", "Ronfe"),
("Portugal", "Roque"),
("Portugal", "Roriz"),
("Portugal", "Runa"),
("Portugal", "Sabugal"),
("Portugal", "Sacavem"),
("Portugal", "Salreu"),
("Portugal", "Salto"),
("Portugal", "Salvaterra de Magos"),
("Portugal", "Samil"),
("Portugal", "Samora Correia"),
("Portugal", "Samouco"),
("Portugal", "Sandim"),
("Portugal", "Sanfins do Douro"),
("Portugal", "Sangalhos"),
("Portugal", "Sanguedo"),
("Portugal", "Santa Barbara de Nexe"),
("Portugal", "Santa Catarina"),
("Portugal", "Santa Catarina da Serra"),
("Portugal", "Santa Clara-a-Velha"),
("Portugal", "Santa Comba Dao"),
("Portugal", "Santa Cruz"),
("Portugal", "Santa Iria da Azoia"),
("Portugal", "Santa Marta"),
("Portugal", "Santa Marta de Penaguiao"),
("Portugal", "Santana"),
("Portugal", "Santiago"),
("Portugal", "Santiago"),
("Portugal", "Santiago da Guarda"),
("Portugal", "Santiago de Riba-Ul"),
("Portugal", "Santiago do Cacem"),
("Portugal", "Santo Andre"),
("Portugal", "Santo Antao do Tojal"),
("Portugal", "Santo Antonio"),
("Portugal", "Santo Antonio da Charneca"),
("Portugal", "Santo Tirso"),
("Portugal", "Sao Bras"),
("Portugal", "Sao Bras de Alportel"),
("Portugal", "Sao Domingos de Rana"),
("Portugal", "Sao Felix da Marinha"),
("Portugal", "Sao Francisco"),
("Portugal", "Sao Joao"),
("Portugal", "Sao Joao da Madeira"),
("Portugal", "Sao Joao da Talha"),
("Portugal", "Sao Joao das Lampas"),
("Portugal", "Sao Joao de Ver"),
("Portugal", "Sao Joao do Campo"),
("Portugal", "Sao Joao dos Montes"),
("Portugal", "Sao Juliao do Tojal"),
("Portugal", "Sao Mamede de Infesta"),
("Portugal", "Sao Marcos"),
("Portugal", "Sao Pedro da Cadeira"),
("Portugal", "Sao Pedro do Estoril"),
("Portugal", "Sao Romao do Coronado"),
("Portugal", "Sao Roque"),
("Portugal", "Sao Vicente da Beira"),
("Portugal", "Sao Vicente de Lafoes"),
("Portugal", "Sardoal"),
("Portugal", "Sarilhos Grandes"),
("Portugal", "Satao"),
("Portugal", "Seia"),
("Portugal", "Seixal"),
("Portugal", "Seixal"),
("Portugal", "Sendim"),
("Portugal", "Senhora da Hora"),
("Portugal", "Seroa"),
("Portugal", "Serpa"),
("Portugal", "Serpins"),
("Portugal", "Serta"),
("Portugal", "Sesimbra"),
("Portugal", "Sete Rios"),
("Portugal", "Sever do Vouga"),
("Portugal", "Silva"),
("Portugal", "Silvares"),
("Portugal", "Silveira"),
("Portugal", "Silves"),
("Portugal", "Sines Municipality"),
("Portugal", "Sintra"),
("Portugal", "Soalheira"),
("Portugal", "Sobrado"),
("Portugal", "Sobrado de Paiva"),
("Portugal", "Sobral de Monte Agraco"),
("Portugal", "Sobralinho"),
("Portugal", "Sobreda"),
("Portugal", "Sobreiro"),
("Portugal", "Sobrosa"),
("Portugal", "Soito"),
("Portugal", "Soure Municipality"),
("Portugal", "Souto da Carpalhosa"),
("Portugal", "Souzel"),
("Portugal", "Sul"),
("Portugal", "Tabuaco"),
("Portugal", "Talaide"),
("Portugal", "Tamel"),
("Portugal", "Tarouca"),
("Portugal", "Taveiro"),
("Portugal", "Tavira Municipality"),
("Portugal", "Teixoso"),
("Portugal", "Telhado"),
("Portugal", "Tercena"),
("Portugal", "Terena"),
("Portugal", "Tires"),
("Portugal", "Tocha"),
("Portugal", "Tomar"),
("Portugal", "Tondela"),
("Portugal", "Torre da Marinha"),
("Portugal", "Torre de Moncorvo"),
("Portugal", "Torres Novas"),
("Portugal", "Torres Vedras"),
("Portugal", "Touguinha"),
("Portugal", "Tourais"),
("Portugal", "Trafaria"),
("Portugal", "Trancoso"),
("Portugal", "Trancoso de Baixo"),
("Portugal", "Travanca"),
("Portugal", "Treixedo"),
("Portugal", "Trofa"),
("Portugal", "Tunes"),
("Portugal", "Turcifal"),
("Portugal", "Vagos"),
("Portugal", "Valado de Frades"),
("Portugal", "Valbom"),
("Portugal", "Vale"),
("Portugal", "Vale"),
("Portugal", "Vale"),
("Portugal", "Vale da Pinta"),
("Portugal", "Vale de Acor"),
("Portugal", "Vale de Cambra"),
("Portugal", "Valega"),
("Portugal", "Valenca"),
("Portugal", "Valongo"),
("Portugal", "Valverde"),
("Portugal", "Varzea do Douro"),
("Portugal", "Venda do Pinheiro"),
("Portugal", "Vendas Novas"),
("Portugal", "Vermelha"),
("Portugal", "Vermoil"),
("Portugal", "Vialonga"),
("Portugal", "Viana do Alentejo"),
("Portugal", "Viana do Castelo"),
("Portugal", "Vidago"),
("Portugal", "Vidigueira"),
("Portugal", "Vieira de Leiria"),
("Portugal", "Vieira do Minho"),
("Portugal", "Vila Alva"),
("Portugal", "Vila Boa de Quires"),
("Portugal", "Vila Cha"),
("Portugal", "Vila Cha de Ourique"),
("Portugal", "Vila de Porto Santo"),
("Portugal", "Vila do Bispo"),
("Portugal", "Vila do Conde"),
("Portugal", "Vila Franca de Xira"),
("Portugal", "Vila Franca do Rosario"),
("Portugal", "Vila Nogueira de Azeitao"),
("Portugal", "Vila Nova"),
("Portugal", "Vila Nova"),
("Portugal", "Vila Nova"),
("Portugal", "Vila Nova"),
("Portugal", "Vila Nova da Barquinha"),
("Portugal", "Vila Nova de Cerveira"),
("Portugal", "Vila Nova de Famalicao"),
("Portugal", "Vila Nova de Gaia"),
("Portugal", "Vila Nova de Paiva"),
("Portugal", "Vila Praia de Ancora"),
("Portugal", "Vila Real"),
("Portugal", "Vila Verde"),
("Portugal", "Vilar de Perdizes"),
("Portugal", "Vilar do Paraiso"),
("Portugal", "Vilar do Pinheiro"),
("Portugal", "Vilar Formoso"),
("Portugal", "Vilarinho das Paranheiras"),
("Portugal", "Vilarinho de Arcos"),
("Portugal", "Vilarinho do Bairro"),
("Portugal", "Vilela"),
("Portugal", "Vimieiro"),
("Portugal", "Vinhais"),
("Portugal", "Viseu"),
("Portugal", "Vizela"),
("Portugal", "Vizela"),
("Portugal", "Zambujal"),
("Portugal", "Zibreira");