INSERT INTO subjects (name) VALUES
('Mathematics'),
('Portuguese'),
('History'),
('Geography'),
('Natural Sciences'),
('Physical Education'),
('English'),
('Arts'),
('Philosophy'),
('Biology'),
('Chemistry'),
('Physics'),
('Computer Science'),
('Sociology'),
('Economics'),
('Civic Education'),
('Foreign Language'),
('Literature'),
('Religious Studies'),
('Music'),
('Psychology'),
('Environmental Studies'),
('Anthropology'),
('Business Studies'),
('Drama'),
('Health Education'),
('Law'),
('Media Studies'),
('Design and Technology'),
('Home Economics'),
('Information Technology'),
('Agricultural Science'),
('Engineering'),
('Architecture'),
('Fashion and Textile Design'),
('Hospitality and Tourism'),
('Film Studies'),
('French'),
('Spanish'),
('German'),
('Mandarin'),
('Japanese'),
('Italian'),
('Russian'),
('Arabic'),
('Latin'),
('Korean'),
('Dutch'),
('Swedish'),
('Greek'),
('Polish'),
('Indonesian'),
('Vietnamese'),
('Advanced Mathematics'),
('Literary Theory'),
('Political Science'),
('International Relations'),
('Microeconomics'),
('Macroeconomics'),
('Computer Engineering'),
('Artificial Intelligence'),
('Robotics'),
('Neuroscience'),
('Biochemistry'),
('Organic Chemistry'),
('Astrophysics'),
('Quantum Mechanics'),
('Environmental Law'),
('Civil Engineering'),
('Urban Planning'),
('Fashion Design'),
('Culinary Arts'),
('Film Production'),
('Psychology of Human Behavior'),
('Algebra');
