---
profile:
  name: Profile
  icon: home
  route: /km/profile
  component: km-profile-page
  role: [0, 1]
classes:
  name: Classes
  icon: calendar
  route: /km/classes
  role: [1]
contracts:
  name: Contracts
  icon: message
  route: /km/contracts
  component: km-contracts-page
  role: [1]
proposals:
  name: Proposals
  icon: message
  component: km-proposals-page
  route: /km/proposals
  role: [0]
professores:
  name: Find Teachers
  icon: groupPeople
  route: /km/professores
  component: km-professores-page
  role: [0]
